check/urls.py
from django.urls import path, re_path
from .views import check_num, check_word, ajax_type, ajax_save, check_result

urlpatterns = [
    path('', check_num),
    path('ajax_type', ajax_type),
    path('ajax_save', ajax_save),
    re_path(r'(?P<check_id>[0-9]{4,5}?)/result/$', check_result),
    re_path(r'(?P<check_id>[0-9]{4,5}?)/$', check_word),

]

home/urls.py
from django.urls import path
from home import views


urlpatterns = [
    path('', views.index),
    path('index/', views.index),
]

word/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls import include
from word.settings import MEDIA_ROOT
from django.views.static import serve
import login.views
import captcha.views
import user.urls
import home.urls
import check.urls
import user.views
import note.urls

urlpatterns = [

    re_path(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),

    path('admin/', admin.site.urls),
    # login 模块
    path('login/', login.views.login),
    path('logout/', login.views.logout),
    path('register/', login.views.register),
    path('confirm/', login.views.user_confirm),
    path('forget/', login.views.forget),
    path('reset/', login.views.reset),
    path('ajax_reset', login.views.ajax_reset),

    # 验证码
    path('captcha/', include('captcha.urls')),
    path('ajax_val', login.views.ajax_val, name='ajax_val'),
    path('refresh', captcha.views.captcha_refresh, name='captcha-refresh'),

    # 用户
    re_path(r'user/', include(user.urls)),
    # re_path(r'user/([\w]+)/', user.views.user_info),

    # 首页
    path('', include(home.urls)),

    # 单词检测
    path('check/', include(check.urls)),

    # 笔记
    path('note/', include(note.urls))

]

check/models.py
from django.db import models

# Create your models here.
# Create your models here.
class Check(models.Model):
    # id, user, create_time, if_finish,
    id = models.AutoField(primary_key=True, verbose_name='ID')
    username = models.CharField(max_length=64, verbose_name='用户名') 
    finish = models.BooleanField(verbose_name='if_finish')
    c_time = models.DateTimeField(auto_now_add=True)
    # last_edit = models.DateTimeField(auto_now=True)
    finish_time = models.DateTimeField(null=True, auto_now=True)
    # R 表示随机，L(random) 表示按首字母来选择
    type = models.CharField(verbose_name='CheckType', max_length=1, default='r')
    check_num = models.IntegerField(default=10)

    def __str__(self) -> str:
        return str(self.id) +  self.username 

    class Meta:
        ordering = ['-id']
        verbose_name = '检查纪录'
        verbose_name_plural = '检查纪录'


class CheckWordR(models.Model):
    # id, check, word time, if_do error_correct
    check_id = models.IntegerField(verbose_name='CheckID')
    username = models.CharField(max_length=64, verbose_name='用户名', default='null') 
    word = models.CharField(verbose_name='ENGWORD', max_length=20)
    result_word = models.CharField(verbose_name='ResultWord', max_length=20, default='')
    error_or_correct = models.BooleanField(null=True)
    if_do = models.BooleanField()
    

    def __str__(self) -> str:
        return str(self.check_id) + ": " +self.word

    class Meta:
        ordering = ['-check_id']
        verbose_name = '随机单词'
        verbose_name_plural = '随机单词'

class CheckWordL(models.Model):
    check_id = models.IntegerField(verbose_name='CheckID')
    username = models.CharField(max_length=64, verbose_name='用户名', default='null') 
    word = models.CharField(verbose_name='ENGWORD', max_length=20)
    result_word = models.CharField(verbose_name='ResultWord', max_length=20, default='')
    error_or_correct = models.BooleanField(null=True)
    if_do = models.BooleanField()
    letter = models.CharField(default='a', max_length=1)

    def __str__(self) -> str:
        return str(self.check_id) + ": " + self.word

    class Meta:
        ordering = ['-check_id']
        verbose_name = '首字母单词'
        verbose_name_plural = '首字母单词'

# class ErrorWord(models.Model):
class ResultWord(models.Model):
    check_id = models.IntegerField(verbose_name='CheckID')
    error_num = models.IntegerField(verbose_name='错误数')
    score = models.FloatField(verbose_name='Score')
    c_time = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return str(self.check_id) + ": " + str(self.score)

    class Meta:
        ordering = ['-c_time']
        verbose_name = '结果'
        verbose_name_plural = '结果'

check/views.py
import word
from django.http.response import JsonResponse
from django.shortcuts import render
from .models import Check, CheckWordL, CheckWordR, ResultWord
import login.models
import user.models
import home.models
import random

# Create your views here.


def check_num(request):
    if not request.session.get('is_login', None):
        login = False
        url = '/login/'
        message = '你还未登录，请登录后再操作'
        return render(request, 'buff.html', locals())
    login = True
    username = request.session.get('user_name')
    # 如果有未完成的，提示完成
    check_li = Check.objects.filter(username=username, finish=False)
    if check_li:
        check_id = check_li[0].id
        message = 'It has unfinished Check, confirm to Check, Or cancel to create a new Check?'
        # print(message)
        return render(request, 'check/check.html', locals())
    return render(request, 'check/check.html', locals())


def check_word(request, check_id):
    login = True
    if not request.session.get('is_login', None):
        login = False
        message = '你还未登录，请登录后再操作'
        url = '/login/'
        return render(request, 'buff.html', locals())
    username = request.session.get('user_name')
    check_li = Check.objects.filter(id=check_id)
    if not check_li:
        message = 'Something error, There are no this page!'
        url = '/check/'
        return render(request, 'buff.html', locals())
    check = check_li[0]
    if check.username != username:
        message = "You don't have authority to visit the page!"
        url = '/check/'
        return render(request, 'buff.html', locals())

    if check.type == 'r':
        word_list = CheckWordR.objects.filter(check_id=check.id)
    else:
        word_list = CheckWordL.objects.filter(check_id=check.id)

    words_dict = {}
    for i in word_list:
        enword = home.models.EnWords.objects.get(word=i.word)
        words_dict[i.word] = enword.translation

    return render(request, 'check/check_word.html', locals())


def get_words(word_type):
    if word_type == "cet-4":
        words = home.models.EnWords.objects.filter(cet4=True)
    elif word_type == "cet-6":
        words = home.models.EnWords.objects.filter(cet6=True)
    elif word_type == "highschool":
        words = home.models.EnWords.objects.filter(highschool=True)
    else:
        words = home.models.EnWords.objects.filter(other_type=word_type)
    # print(len(words))
    return words


def get_random_word(all_words, num, username):
    num = int(num)
    # 找到做过题单词
    did_words = CheckWordR.objects.filter(username=username)
    # 检查是否已经做过
    did_word = list(map(lambda x: x.word, did_words))
    words = list(filter(lambda x: x.word not in did_word, all_words))
    # print(len(all_words))
    res_list = []
    # 如果已经小于对应的num了，那么就要从做过的题随机选了
    if len(words) < num:
        lass_num = num - len(words)
        res_list = list(words) + random.sample(did_words, lass_num)
    else:
        # 产生相对应数量的不重复的随机数
        res_list = random.sample(words, num)
    return list(res_list)


def get_letter_word(all_words, letter, num, username):
    num = int(num)
    letter_words = filter(lambda x: x.word.startswith(letter), all_words)
    did_words = CheckWordL.objects.filter(letter=letter, username=username)
    words = list(filter(lambda x: x.word not in did_words, letter_words))

    if len(words) >= num:
        return list(words)[:num]
    # 如果不够，那就再随机选做过的的
    lass_num = num - len(words)
    return list(words) + random.sample(did_words, lass_num)


def save_check(words: list, check_s: Check, username: str, letter: str):
    type = check_s.type
    check_id = check_s.id
    for word in words:
        if type.lower() == 'r':
            check_word = CheckWordR()
        else:
            check_word = CheckWordL()
            check_word.letter = letter

        check_word.username = username
        check_word.check_id = check_id
        check_word.word = word.word
        check_word.if_do = False
        check_word.save()
    return True

# 创建Check


def ajax_type(request):
    if not request.is_ajax():
        data = {'status': 0, 'message': 'Maybe submit again?', }
        return JsonResponse(data)
    if not request.session.get('user_name', None):
        data = {'status': 0, 'message': 'Please login!', }
        return JsonResponse(data)
    username = request.session.get('user_name')
    select_type = request.POST.get('type')[0]
    letter = request.POST.get('letter')
    num = request.POST.get('num')

    try:
        word_type = user.models.UserWord.objects.get(username=username)
    except:
        data = {
            'status': 0, 'message': 'Please select the <a href="/user/select_word"> word_type </a>first!'}
        return JsonResponse(data)
    words = get_words(word_type.word_type)
    if select_type.lower() == 'r':
        words_list = get_random_word(words, num, username)
    else:
        words_list = get_letter_word(words, letter, num, username)

    check_0 = Check()
    check_0.username = username
    check_0.type = select_type
    check_0.finish = False
    check_0.check_num = int(num)
    check_0.save()
    save_check(words_list, check_0, username, letter)

    dy = user.models.Dynamics()
    dy.add_dynamics(username, type=select_type.upper(), target_id=check_0.id,
                    doing="create a new test check of {} words.".format(num))
    return JsonResponse({'status': 1, 'url': '/check/{}'.format(check_0.id)})


def finish(request):
    return render(request, 'check/finish.html', locals())


def if_exit(did_words: list, enword):
    for i in did_words:
        if i.word == enword.word:
            return False
    return True


# 保存Test
def ajax_save(request):
    if not request.is_ajax():
        data = {'status': 0, 'messsaage': 'Request Again?'}
        return JsonResponse(data)
    answers = request.POST.getlist('answer')
    words = request.POST.getlist('words')
    print(answers, words)
    check_id = request.POST.get("check_id")
    # print(request.POST)
    check_words = CheckWordR.objects.filter(check_id = check_id)
    if not check_words:
        check_words = CheckWordL.objects.filter(check_id=check_id)

    for check_word in check_words:
        index = words.index(check_word.word)
        check_word.if_do = True
        if answers[index] == check_word.word:
            check_word.error_or_correct = True
        else:
            check_word.error_or_correct = False
        check_word.result_word = answers[index]
        check_word.save()
    
    check = Check.objects.get(id=check_id)
    check.finish = True
    check.save()

    error_num = 0
    for i in range(len(words)):
        if words[i] != answers[i]:
            error_num += 1

    correct_num = len(words) - error_num
    score = (correct_num / len(words)) * 100

    rw = ResultWord()
    rw.check_id = check_id
    rw.error_num = error_num
    rw.score = score
    rw.save()

    dy = user.models.Dynamics()
    dy.add_dynamics(check.username, type='F', target_id=check_id, doing="Finish ther {} test check of {} words.".format(check_id, check_num))
    return JsonResponse({'status': 1, 'message': 'submit success', 'url': 'check/{}/result'.format(check_id)}) 

def check_result(request, check_id):
    if not request.session.get('is_login', None):
        login = False
        message = '你还未登录，请登录后再操作'
        url = '/login/'
        return render(request, 'buff.html', locals())
    username = request.session.get('user_name')
    check_li = Check.objects.filter(id=check_id)
    if not check_li:
        message = 'Something error, There are no this page!'
        url = '/check/'
        return render(request, 'buff.html', locals())
    check = check_li[0]
    if check.username != username:
        message = "You don't have authority to visit the page!"
        url = '/check/'
        return render(request, 'buff.html', locals())

    rw = ResultWord.objects.filter(check_id=check_id)
    if not rw:
        message = "Please finish the chek!"
        url = '/check/{}'.format(check_id)
        return render(request, 'buff.html', locals())

    if check.type == 'r':
        words = CheckWordR.objects.filter(check_id=check.id)
    else:
        words = CheckWordL.objects.filter(check_id=check.id)

    trans = []
    for i in words:
        enword = home.models.EnWords.objects.get(word=i.word)
        trans.append(enword.translation)
    num = check.check_num
    range_for = range(num)
    score = rw[0].score
    return render(request, 'check/check_result.html', locals())

templates/check/check.html
{% extends 'base.html' %}

{% block title %}
Check
{% endblock title %}




{% block style %}
<style>
    .center-block {
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
</style>
{% endblock style %}

{% block body %}

<button type="button" id="something_id" class="btn btn-primary hidden" data-toggle="modal" data-target="#somethingModal">Large modal</button>
<div class="modal fade" id="somethingModal" tabindex="-1" role="dialog" aria-labelledby="somethingModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="resetModalLabel">check</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
            </div>
            <div class="modal-body" id="check_modal_body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" id="check_cancel">
                    cancel
                </button>
                <button type="button" class="btn btn-primary" id="check_certain">certain</button>
            </div>
        </div>
    </div>
</div>

<div class="container ">
    <form action="" id="type_form">
        <div class="row">
            <div id="type_alert" class="hidden alert alert-warning col-md-3 col-xs-10 col-xs-offset-1 col-md-offset-3">

            </div>
        </div>
        {% csrf_token %}
        <div class="row">
            <div class="form-group col-md-3 col-md-offset-3">
                <label for="id_type">Type:</label>
                <ul id="id_type" class="Radio">
                    <li><label for="id_random"><input type="radio" name="type" value="random" class="Radio" required=""
                                id="id_random" checked>
                            random</label>

                    </li>
                    <li><label for="id_first_letter"><input type="radio" name="type" value="letter" class="Radio"
                                required="" id="id_first_letter">
                            first_letter</label>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-4 col-md-offset-3 hidden" id="id_letter_div">
                <label for="id_letter">First Letter:
                    <input type="text" class="form-control " name="letter" id="id_letter" maxlength="1"
                        oninput="this.value=this.value.replace(/[^a-zA-Z]/g,'')">
                </label>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-3 col-md-offset-3">
                <label for="num" class="control-label">Select Num: </label>
                <select class="form-control" id="id_num" name='num' value=10>
                    <option id="num_10" value=10>10</option>
                    <option id="num_20" value=20>20</option>
                    <option id="num_30" value=30>30</option>
                    <option id="num_40" value=40>40</option>
                    <option id="num_50" value=50>50</option>
                </select>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-md-offset-3">
                <button type="button" data-toggle="modal" data-target="#selectTypeModal" class="btn btn-primary">Start</button>

                <div class="modal fade" id="selectTypeModal" tabindex="-1" role="dialog" aria-labelledby="SelectTypeModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title" id="SelectTypeModalLabel">check</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                    &times;
                                </button>
                            </div>
                            <div class="modal-body" id="">confirm to create a new check?</div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal" id="word_type_num_cancel">
                                    cancel
                                </button>
                                <button type="button" class="btn btn-primary" id="word_type_num">certain</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock body %}

{% block script %}
<script>
    $(document).ready(
        $(function () {
            {% if message %}
            $('#check_modal_body').text("{{ message }}");
            $('#something_id').click();
            {% comment %} $('#somethingModal').modal('toggle'); {% endcomment %}
            $('#check_certain').click(function(){
                location.href="/check/" + {{ check_id }} + ""
            })
            {% endif %}

            $("#id_first_letter").click(function () {
                $("#id_letter_div").removeClass("hidden");
                $("#id_letter").val('');
            });

            $("#id_random").click(function () {
                $("#id_letter_div").addClass("hidden")
                $("#id_letter").val('a');
            });
            $("#word_type_num").click(function () {
                $.ajax({
                    url: "ajax_type",
                    data: $("#type_form").serialize(),
                    type: "post",
                    datatype: 'json',
                    success: function (result) {
                        console.log(result['status'])
                        if (result['status'] === 0) {
                            $('#type_alert').removeClass('hidden');
                            $('#type_alert').html(result['message']);
                        }
                        else {
                            $('#word_type_num_cancel').click()
                            $('#word_type_num_cancel').click()
                            $('#check_modal_body').text('Create success, Check now? ');
                            $('#something_id').click();
                            $('#check_certain').click(function(){
                                location.href=result['url']
                            })
                        }

                    },
                    error: function (result) {
                    }
                })

            })
        })

    );
</script>
{% endblock script %}

templates/check/check_result.html
{% extends 'base.html' %}

{% block title %}
Check result
{% endblock title %}




{% block style %}
{% endblock style %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-11">
            <div class="table-responsive table-hover">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</td>
                            <th>Word</td>
                            <th>Translate</td>
                            <th>Result</td>
                            <th>Correct</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for word in words %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td class="info">{{ word.word }}</td>
                            <td class="info">{{ word.result_word }}</td>
                            {% for tran in trans %}
                            {% if forloop.counter == forloop.parentloop.counter %}
                            <td class="">{{tran}}</td>
                            {% endif %}
                            {% endfor %}
                            {% if word.error_or_correct %}
                            <td class="success"><span class="glyphicon glyphicon-ok"> </span></td>
                            {% else %}
                            <td class="danger"><span class="glyphicon glyphicon-remove"> </span></td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td>Count</td>
                            <td class="">{{ num }}</td>
                            <td class="">{{ num }}</td>
                            <td class="">{{ num }}</td>
                            <td class="">{{ score }}</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>

        </tfoot>
        </table>
    </div>
</div>

</div>
</div>
{% endblock body %}

templates/check/check_word.html
{% extends 'base.html' %}

{% block title %}
Check
{% endblock title %}




{% block style %}
<style>
    .center-block {
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
</style>
{% endblock style %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-5 col-md-offset-3">
            <form class="form-horizontal">
                {% csrf_token %}
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label" id="">Translation</label>
                    <div class="col-sm-10">
                        <input type="" readonly value="n. 放弃" class="form-control" id="word_tran" maxlength="15"
                            placeholder="word">
                        <!-- <p class="control-p">n. 放弃</p> -->
                    </div>
                </div>
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label" id="">Word</label>
                    <div class="col-sm-10">
                        <input type="text" oninput="this.value=this.value.replace(/[^a-zA-Z]/g,'')" ,
                            class="form-control" id="input_word" maxlength="15" placeholder="word"
                            aria-describedby="inputSuccess3Status">
                        <!-- <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
                        <span id="inputSuccess3Status" class="sr-only">(success)</span> -->
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-offset-2 col-sm-4 col-md-2">
                        <button type="button" class="btn btn-info" id="prev_word">prev</button>
                    </div>
                    <div class="col-md-1 col-md-offset-2">
                        <ins id="current_num">1</ins>/<ins id="word_sum">10</ins>
                    </div>
                    <div class="col-sm-offset-2 col-sm-4 col-md-2 col-md-offset-3">
                        <button type="button" class="btn btn-primary" id="next_word">next</button>
                    </div>
                </div>
                <div style="height: 20px;">
                </div>
                <div class="form-group hidden" id="save_div">
                    <label for="" class="col-sm-2  control-label" id="">Save </label>
                    <div class="col-sm-10">
                        <button type="button" class="btn btn-success" id="save_submit">save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock body %}

{% block script %}
<script>

    $(document).ready(
        $(function () {
            words_dict = {}
            var words = [];
            var words_tran = []
            {% for i, j in words_dict.items %}
            words.push('{{i}}');
            words_tran.push('{{j}}');
            words_dict['{{i}}'] = '{{j}}';
            {% endfor %}
            console.log(words);
            console.log(words_tran);
            console.log(words_dict);
            length = words.length;
            var answer_list = new Array([length]);
            $("#current_num").text(1);
            $("#word_sum").text(length);
            $("#word_tran").val(words_tran[0])
            $("#next_word").click(next_word)
            $("#input_word").keydown(function (e) {
                if (e.keyCode == 13) {
                    next_word();
                }
            });
            function if_over(li, num) {
                if (li.length === num) {
                    return true;
                }
                return false;
            }

            function next_word() {
                current_num = parseInt($("#current_num").text())
                word_sum = parseInt($("#word_sum").text())
                if ($('#input_word').val() === '') {
                    $("#word_status").remove();
                    $('#input_word').after('<span id="word_status" ><small>Please input the word!</small></span>')
                }
                else if (word_sum === current_num) {
                    $("#save_div").removeClass("hidden")
                    answer_list[current_num - 1] = $("#input_word").val();
                }
                else {
                    $("#word_status").remove();
                    answer_list[current_num - 1] = $("#input_word").val();
                    $("#current_num").text(current_num + 1);
                    $("#word_tran").val(words_tran[current_num]);
                    if (answer_list[current_num]) {
                        $("#input_word").val(answer_list[current_num]);
                    }
                    else {
                        $("#input_word").val('');
                    }
                    $("#input_word").focus()
                }
                console.log(answer_list)
                if (if_over(answer_list, word_sum)) {
                    $("#save_div").removeClass("hidden")
                }
            }
            $("#prev_word").click(function () {
                current_num = parseInt($("#current_num").text())
                word_sum = parseInt($("#word_sum").text())

                if (current_num === 1) {
                    $("#word_status").remove();
                    $('#input_word').after('<span id="word_status" ><small>No more previous!</small></span>')
                } else {
                    $("#word_status").remove();
                    $("#current_num").text(current_num - 1);
                    $("#word_tran").val(words_tran[current_num - 2]);
                    answer_list[word_sum - 2] = $("#input_word").val();
                    if (answer_list[current_num - 2]) {
                        $("#input_word").val(answer_list[current_num - 2]);
                    }
                    else {
                        $("#input_word").val('');
                    }
                    $("#input_word").focus()
                }
                if (if_over(answer_list, word_sum)) {
                    $("#save_div").removeClass("hidden")
                }
            })
            $("#save_submit").click(function () {
                // alert("TEST");
                jQuery.ajaxSettings.traditional = true;
                url = location.href;
                url_li = url.split('/');
                check_id = url_li[url_li.length-2];
                // alert(check_id)
                $.ajax({
                    url: "/check/ajax_save",
                    data: { csrfmiddlewaretoken: '{{ csrf_token }}',"check_id": check_id, 'answer': answer_list, 'words': words,  },
                    type: "post",
                    datatype: 'json',
                    success: function (result) {
                        alert(result['message']);
                        if(result['status'] == 1){
                            location.href = '/index/'
                        }
                        
                    },
                    error: function (result) {

                    }
                })
            })
        })
    )

</script>
{% endblock script %}