home/urls.py
from django.urls import path
from home import views


urlpatterns = [
    path('', views.index),
    path('index/', views.index),
]

word/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls import include
from word.settings import MEDIA_ROOT
from django.views.static import serve
import login.views
import captcha.views
import user.urls
import home.urls
import check.urls
import user.views
import note.urls

urlpatterns = [

    re_path(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),

    path('admin/', admin.site.urls),
    # login 模块
    path('login/', login.views.login),
    path('logout/', login.views.logout),
    path('register/', login.views.register),
    path('confirm/', login.views.user_confirm),
    path('forget/', login.views.forget),
    path('reset/', login.views.reset),
    path('ajax_reset', login.views.ajax_reset),

    # 验证码
    path('captcha/', include('captcha.urls')),
    path('ajax_val', login.views.ajax_val, name='ajax_val'),
    path('refresh', captcha.views.captcha_refresh, name='captcha-refresh'),

    # 用户
    re_path(r'user/', include(user.urls)),
    # re_path(r'user/([\w]+)/', user.views.user_info),

    # 首页
    path('', include(home.urls)),

    # 单词检测
    path('check/', include(check.urls)),

    # 笔记
    path('note/', include(note.urls))

]

login/models.py
from re import T
from django.db import models
from django.db.models.deletion import CASCADE
from enum import Enum

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=32,unique=True, null=False, verbose_name='用户名', db_index=True)
    password = models.CharField(max_length=256, null=False, verbose_name='密码')
    email = models.EmailField(verbose_name='邮箱')
    c_time = models.DateTimeField(auto_now_add=True, verbose_name='注册时间')
    has_confirmed = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.username
    
    class Meta:
        ordering = ['-c_time']
        verbose_name = '用户'
        verbose_name_plural = "用户"

# 枚举类
# class SEX(Enum):
#     F = '女'
#     M = '男'
#     S = '保密'

class UserDetail(models.Model):
    user = models.OneToOneField('User', on_delete=CASCADE)
    nickname = models.CharField(max_length=128, default='喵帕斯', verbose_name='昵称')
    gender = (
        ('male', "男"),
        ('female', "女"),
        ('other', '其它')
    )
    sex = models.CharField(max_length=32, choices=gender, default='男')
    sign = models.CharField(
        max_length=256, verbose_name='签名', default='这个人很懒，什么也没有留下！')
    avatar = models.ImageField(upload_to='img', verbose_name='头像')
    birthday = models.DateField(auto_now_add=True)
    last_edit = models.DateTimeField(auto_now=True)
    def __str__(self) -> str:
        return self.user.username + self.nickname

    class Meta:
        ordering = ['-last_edit']
        verbose_name = '用户信息'
        verbose_name_plural = "用户信息"


class ConfirmString(models.Model):
    code = models.CharField(max_length=256)
    user = models.OneToOneField('User', on_delete=CASCADE)
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.user.username + ": " + self.code

    class Meta:
        ordering = ['-c_time']
        verbose_name = '确认码'
        verbose_name_plural = "确认码"


class LoginRecord(models.Model):
    login_user = models.CharField(max_length=128, verbose_name='用户')
    login_time = models.DateTimeField(auto_now_add=True, verbose_name='登录时间')
    login_ip = models.CharField(max_length=31, verbose_name="IP")

    def __str__(self) -> str:
        return self.login_user

    class Meta:
        ordering = ['-login_time']
        verbose_name = '登录纪录'
        verbose_name_plural = "登录纪录"

class ForgetString(models.Model):
    code = models.CharField(max_length=256)
    username = models.CharField(max_length=128)
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.username + ": " + self.code

    class Meta:
        ordering = ['-c_time']
        verbose_name = '重置码'
        verbose_name_plural = "重置码"

login/views.py
import datetime
import hashlib
import pytz

from captcha.models import CaptchaStore
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import redirect, render


from .form import *
# from django.shortcuts import render_to_response
from .models import *
import user.models


def ajax_val(request):
    if request.is_ajax():
        cs = CaptchaStore.objects.filter(
            response=request.GET['response'].lower(), hashkey=request.GET['hashkey'])
        if cs:
            json_data = {'status': 1}
            return JsonResponse(json_data)
        else:
            json_data = {'status': 0}
            return JsonResponse(json_data)
    else:
        json_data = {'status': 0}
        return JsonResponse(json_data)


def login(request):
    l_time = request.session.get('l_time', None)
    if l_time != None:
        l_time = datetime.datetime.strptime(l_time, '%Y-%m-%d %H:%M:%S')
        # 如果登录session超过30天, 就需要重新登录
        if datetime.datetime.now() > l_time + datetime.timedelta(30):
            request.session.flush()
    if request.session.get('is_login', None):
        # 不能重复登录
        return redirect('/index/')
    if request.method == "POST":
        login_form = UserForm(request.POST)
        message = '验证码错误'
        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')

            try:
                user = User.objects.get(username=username)
            except:
                message = '用户不存在'
                return render(request, 'login/login.html', locals())
            if not user.has_confirmed:
                message = "该用户还未经过邮件确认！"
                return render(request, 'login/login.html', locals())

            if user.password == hash_code(password):
                request.session['is_login'] = True
                request.session['user_id'] = user.id
                request.session['user_name'] = user.username
                request.session['l_time'] = datetime.datetime.now().strftime(
                    "%Y-%m-%d %H:%M:%S")
                record_ip(request, user.username)
                return redirect('/index/')
            else:
                message = '密码不正确'
                return render(request, 'login/login.html', locals())
        else:
            return render(request, 'login/login.html', locals())
    login_form = UserForm()
    return render(request, 'login/login.html', locals())


def register(request):
    if request.session.get('is_login', None):
        return redirect('/index/')
    if request.method == "POST":
        register_form = RegisterForm(request.POST)
        message = '验证码错误'
        if register_form.is_valid():
            username = register_form.cleaned_data.get('username')
            password_1 = register_form.cleaned_data.get('password1')
            password_2 = register_form.cleaned_data.get('password2')
            email = register_form.cleaned_data.get('email')

            if password_1 != password_2:
                message = '两次输入的密码不同'
                return render(request, 'login/register.html', locals())
            if len(password_1) < 8:
                message = '输入的密码太短，密码至少8位'
                return render(request, 'login/register.html', locals())
            same_name_user = User.objects.filter(username=username)
            if same_name_user:
                message = '用户名已经存在'
                return render(request, 'login/register.html', locals())
            same_email_user = User.objects.filter(email=email)
            if same_email_user:
                message = '该邮箱已经被注册'
                return render(request, 'login/register.html', locals())

            new_user = User()
            new_user.username = username
            new_user.password = hash_code(password_1)
            new_user.email = email
            new_user.save()

            code = make_confirm_string(new_user)
            send_email(email, code)
            message = '请往邮箱确认！'
            return render(request, 'login/confirm.html', locals())
        return render(request, 'login/register.html', locals())
    register_form = RegisterForm()
    return render(request, 'login/register.html', locals())


def logout(request):
    # 如果没有登录的话，那就去登录吧
    if not request.session.get('is_login', None):
        return redirect("/login/")
    request.session.flush()
    # 或者以下方法
    # del request.session['is_login']
    # del request.session['user_id']
    # del request.session['user_name']
    return redirect('/login/')


def user_confirm(request):
    code = request.GET.get('code', None)
    message = ''
    try:
        confirm = ConfirmString.objects.get(code=code)
    except:
        message = '无效的确认请求'
        return render(request, 'login/confirm.html', locals())
    c_time = confirm.c_time
    # 转人为可对比的时间
    now = datetime.datetime.now()
    now = now.replace(tzinfo=pytz.timezone('UTC'))
    if now > c_time + datetime.timedelta(settings.CONFIRM_DAYS):
        confirm.user.delete()
        message = "你的邮件已经过期！请重新注册！"
        return render(request, 'login/confirm.html', locals())
    confirm.user.has_confirmed = True
    confirm.user.save()
    confirm.delete()
    message = '感谢确认，请使用账户登录！'
    return render(request, 'login/confirm.html', locals())


def hash_code(s, salt='nyanpasu'):
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())
    return h.hexdigest()


def make_confirm_string(user: User):
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    code = hash_code(user.username, now)
    ConfirmString.objects.create(code=code, user=user)
    return code


def send_email(email, code, type='R'):
    from django.core.mail import EmailMultiAlternatives
    if type == 'R':
        subject = '来自 悠哉网 的注册确认邮件'
        text_content = '''欢迎注册道理的悠哉网，这里是道理的各种笔记。
        如果你看到这条消息，说明你的邮箱服务器不提供HTML链接功能，请联系管理员！
        '''
        html_content = '''
        <p> 感谢注册<a href="http://{}/confirm/?code={}" target=blank>jinl1874.xyz</a>的博客网站。</p>
        <p> 请点击站点链接完成注册确认！</p>
        <p> 此链接有效期为{}天</p>
        '''.format('127.0.0.1:8000', code, settings.CONFIRM_DAYS)
    else:
        subject = '来自 悠哉网 的重置确认邮件'
        text_content = '''欢迎来到道理的悠哉网，这里是道理的各种笔记。
        如果你看到这条消息，说明你的邮箱服务器不提供HTML链接功能，请联系管理员！
        '''
        html_content = '''
        <p><a href="http://{}/reset/?code={}" target=blank>link</a></p>
        <p> 请点击站点链接完成重置！</p>
        <p> 此链接有效期为{}天</p>
        '''.format('127.0.0.1:8000', code, 1)
    msg = EmailMultiAlternatives(
        subject, text_content, settings.EMAIL_HOST_USER, [email])
    msg.attach_alternative(html_content, 'text/html')
    msg.send()


def record_ip(request, username):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')

    lr = LoginRecord()
    lr.login_user = username
    lr.login_ip = ip
    lr.save()
    

def forget(request):
    status = 'fail'
    if request.method == 'POST':
        forget_form = ForgetForm(request.POST)
        if forget_form.is_valid():
            email = forget_form.cleaned_data.get('email')
            username = forget_form.cleaned_data.get('username')
            try:
                user = User.objects.get(email=email)
                user_1 = User.objects.get(username=username)
                if user.id != user_1.id:
                    message = '邮箱或用户错误，请重新输入'
                    return render(request, 'login/forget.html', locals())
            except:
                message = '邮箱或用户不存在，请重新输入'
                return render(request, 'login/forget.html', locals())
            
            now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            code = hash_code(user.username, now+'forget')
            ForgetString.objects.create(code=code, username=user.username)
            # send_email('email', code, type='F')
            message = '已经发送重置链接邮件到邮箱，请前往邮箱！'
            status = 'success'
            return render(request, 'login/forget.html', locals())
    forget_form = ForgetForm()
    return render(request, 'login/forget.html', locals())

def ajax_reset(request):
    if not request.is_ajax():
        data = {'status': 0, 'message': '也许重新点进来看下？',}
        return JsonResponse(data)
    reset_form = ResetForm()
    pwd = request.POST['password1']
    pwd_2 = request.POST['password2']
    code = request.POST['code']
    message = reset_form.check(pwd, pwd_2, code)
    if message != 'True':
        data = {
            'status': 0,
            'message': message,
        }
        return JsonResponse(data)
    pwd = hash_code(pwd)
    print(code)
    reset_form.save(pwd, code)
    message = '修改成功，请重新登录！'
    data = {
            'status': 1,
            'message': message,
    }
    return JsonResponse(data)
    


def reset(request):
    print("*"*18)
    # fail 失败，success 成功，
    status = 'fail'
    reset_form = ResetForm()
    return render(request, 'login/reset.html', locals())
    # if not reset_form.is_valid():
    #     message = '请检查输入'
    #     return render(request, 'login/reset.html', locals())

    # code = reset_form.cleaned_data.get('code')
    # try:
    #     forget_0 = ForgetString.objects.get(code=code)
    # except:
    #     message = "无效的重置密码请求，请前往邮箱查看！"
    #     return render(request, 'login/reset.html', locals())

    # c_time = forget_0.c_time
    # # 转人为可对比的时间
    # now = datetime.datetime.now()
    # now = now.replace(tzinfo=pytz.timezone('UTC'))
    # if now > c_time + datetime.timedelta(1):
    #     message = "你的邮件已经过期！请重新前往<a href='/forget/'>忘记密码</a>发送邮件！"

templates/login/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <script src="{% static 'js/jquery.min.js' %}"></script> -->
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
    <!-- <link href="{% static 'css/register.css' %}" rel="stylesheet"> -->
    <!-- <script src="{% static 'js/bootstrap.min.js' %}"></script> -->
    <title>{% block title %} {% endblock %}</title>
    {% block css %}

    {% endblock %}
</head>

<body>
    {% block body%}
    {% endblock %}


    {% block endscript %}
    {% endblock %}
</body>

</html>

templates/login/confirm.html
{% extends 'login/base.html' %} 

{% block title %} 注册确认 {% endblock %} 

{% block body %}

<div class='page-header' >
 <h1>{{message}}</h1>
 <p><ins id='timer'></ins> 秒后跳转至登录页</p>
  <p><a class="btn btn-primary" href="/login/" role="button">跳转</a></p>
</div>
<script>
(function() {
    var time = 6;
    $('#timer').text(time)
    var set = setInterval(function() {
        time--;
        $('#timer').text(time);
        if(time === 0) {
            window.location = '/login/'
            clearInterval(set);
        }
    }, 1000);
})();

</script>
{% endblock %}

templates/login/forget.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Forget Password
{% endblock title %}

{% block body %}
<div class="container">

    <form action="/forget/" method="POST" class="col-md-4 col-xs-8 col-md-offset-4 col-xs-offset-2">
        {% csrf_token %}
        {% if message %}
        {% ifequal status 'success' %}
        <div class="alert alert-success" role="alert">{{ message }} </div>
        {% else %}
        <div class="alert alert-warning" role="alert">{{ message }}</div>
        {% endifequal %}
        {% endif %}

        <h4 class="text-center">Forget Password</h4>

        <div class="form-group">
            {{ forget_form.username.label_tag }} {{ forget_form.username}}
        </div>
        <div class="form-group">
            {{ forget_form.email.label_tag }} {{ forget_form.email}}
        </div>
        <div class="form-group">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#forgetModal">
                    send
                </button>
        </div>

        <div class="modal fade" id="forgetModal" tabindex="-1" role="dialog" aria-labelledby="forgetModalLabel"
            aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="forgetModalLabel">确定</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            &times;
                        </button>
                    </div>
                    <div class="modal-body">是否发送重置密码邮件吗？</div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            取消
                        </button>
                        <button type="submit" class="btn btn-primary">确定</button>
                    </div>
                </div>
            </div>
        </div>
    </form>


    {% endblock body %}

    {% block script %}
    <!-- <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
  <script src="https://cdn.bootcss.com/popper.js/1.15.0/umd/popper.js"></script>
  <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script> -->
    {% endblock script %}

templates/login/login.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
{% endblock %}

{% block title %}
登录
{% endblock title %}

{% block style %}
<style>
    body {
        background-image: url("{% static 'img/bg-signin.jpg' %}");
    }
</style>
{% endblock style %}

{% block body %}
<div class="container">

    <form action="/login/" method="POST" class="form-login">
        {% csrf_token %}
        {% if message %}
        <div class="row">
            <div class="alert alert-warning col-md-4 col-xs-10 col-xs-offset-1 col-md-offset-4">
                {{message}}
            </div>
        </div>
        {% endif%}
        <div class="row">
            <div class="col-md-4 col-xs-10 col-xs-offset-1 col-md-offset-4">
                <h3 class="form-center">Welcome Login</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-xs-10 col-xs-offset-1 col-md-offset-4">
                <div class="form-group">
                    {{ login_form.username.label_tag }}
                    {{ login_form.username}}
                </div>

            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-xs-10 col-xs-offset-1 col-md-offset-4">
                <div class="form-group">
                    {{ login_form.password.label_tag }}
                    {{ login_form.password}}
                </div>

            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-xs-10 col-xs-offset-1 col-md-offset-4">
                <div class="form-group">
                    {{ login_form.captcha.label_tag }}
                    {{ login_form.captcha}}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-xs-3 col-xs-offset-1 col-md-offset-4">
                <div class="row">
                    <div class="col-md-1">
                        <a href="/register/" class="btn btn-default">
                            <ins>注册</ins>
                        </a>
                    </div>

                    <div class="col-md-1 col-md-offset-3 ">
                        <a href="/forget/" class="btn btn-linkk">
                            <ins>忘记密码?</ins>
                        </a>
                    </div>
                    <div class="col-md-1 col-md-offset-5 ">
                        <button type="submit" class="btn btn-primary float-right">
                            登录
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>

</div>

{% endblock body %}


{% block script %}
<script>
    $(function () {
        $('.captcha').css({
            'cursor': 'pointer'
        })
        // # ajax 刷新
        $('.captcha').click(function () {
            $("#id_captcha_1").val('');
            $('#captcha_status').remove();
            $.getJSON("/captcha/refresh/",
                function (result) {
                    $('.captcha').attr('src', result['image_url']);
                    $('#id_captcha_0').val(result['key'])
                });
        });
        // 监听输入框的改变，如果验证码正确则显示正确，反之亦然
        $('#id_captcha_1').on('input propertychange', function () {
            json_data = {
                'response': $('#id_captcha_1').val(),  // 获取输入框和隐藏字段id_captcha_0的数值
                'hashkey': $('#id_captcha_0').val()
            }
            $.getJSON('/ajax_val', json_data, function (data) { //ajax发送            
                $('#captcha_status').remove()
                if (data['status']) { //status返回1为验证码正确， status返回0为验证码错误， 在输入框的后面写入提示信息
                    $('#id_captcha_1').after('<span id="captcha_status" >*验证码正确</span>')
                } else {
                    $('#id_captcha_1').after('<span id="captcha_status" >*验证码错误</span>')
                }
            });
        });
    })
</script>
{% endblock script %}

templates/login/reset.html
{% extends 'base.html' %}
{% block title %} 重置密码 {% endblock title%}
{% block body %}
<div class="container">
    <div class="row">
        <div class='form-group col-md-3 col-xs-8 col-md-offset-4 col-xs-offset-2' style="margin-top: 60px;">
            <form id="r_form">
                {% csrf_token %}
                <div></div>
                <div class="alert hidden" role="alert" id='message_alert'></div>

                <h4 class="text-center">重置密码</h3>
                    <div class="form-group">
                        <label for="id_p1">新密码:</label> <input type="password" name="password2" class="form-control"
                            placeholder="new_password" maxlength="256" required id="id_p1">
                    </div>
                    <div class="form-group">
                        <label for="id_p2">确认密码:</label> <input type="password" name="password2" class="form-control"
                            placeholder="new_password" maxlength="256" required id="id_p2">
                    </div>
                    <div class="form-group hidden">
                        {{ reset_form.password1.label_tag }} {{ reset_form.password1 }}
                    </div>
                    <div class="form-group hidden">
                        {{ reset_form.password2.label_tag }} {{ reset_form.password2 }}
                    </div>
                    <div class="hidden">
                        {{ reset_form.code.label_tag }} {{ reset_form.code}}
                    </div>
                    <div class="form-group">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#resetModal">
                            reset
                        </button>
                        <div class="modal fade" id="resetModal" tabindex="-1" role="dialog"
                            aria-labelledby="resetModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title" id="resetModalLabel">确定</h4>
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                            &times;
                                        </button>
                                    </div>
                                    <div class="modal-body">是否要重置密码？</div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal" id="cancel">
                                            取消
                                        </button>
                                        <button type="button" class="btn btn-primary" id="ajax_submit">确定</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </form>
        </div>
    </div>
    {% endblock body %}

    {% block script %}
    <script>
        function set_code() {
            search_str = window.location.search;
            code_list = search_str.split('=');
            if (code_list.length === 2) {
                $('#id_code').val(code_list[1]);
            }
            else {
                $('#id_code').val('None');
            }
        }
        set_code();

        $(document).ready(
            $(function () {
                $('#id_p1').on('input propertychange', function () {
                    $('#id_password1').val($('#id_p1').val());
                })
                $('#id_p2').on('input propertychange', function () {
                    $('#id_password2').val($('#id_p2').val());
                })
                $("#ajax_submit").click(function () {
                    // alert("SOMETHING")
                    $('#cancel').click()
                    $('#cancel').click()
                    $.ajax({
                        url: "/ajax_reset",
                        data: $("#r_form").serialize(),
                        type: "post",
                        datatype: 'json',
                        success: function (result) {
                            console.log(result['status'])
                            if (result['status'] === 0) {
                                // alert()
                                $('#message_alert').removeClass('hidden');
                                $('#message_alert').addClass('alert-warning');
                                $('#message_alert').html(result['message']);
                            }
                            else {
                                $('#message_alert').removeClass('hidden');
                                $('#message_alert').removeClass('alert-warning');
                                $('#message_alert').addClass('alert-success');
                                $('#message_alert').text(result['message']);
                            }
                        },
                        error: function (result) {
                            $('#message_alert').removeClass('hidden');
                            $('#message_alert').addClass('alert-warning');
                            $('#message_alert').text("也许是网络问题？");
                        }
                    })

                })
            })
        );
        // $('#reset_pwd_form').submit(function(){
        //     parent.layer.close(index);
        //     $.ajax({
        //         type: "POST",
        //         dataType: "json",
        //         url: "/ajax_reset",
        //         data: $("#reset_pwd_form").serialize(),
        //         success: function(result){
        //             alert(result)
        //         },
        //         error: function() {
        //             alert("异常")
        //         }
        //     })
        // });
    </script>
    {% endblock script %}