home/urls.py
from django.urls import path
from home import views


urlpatterns = [
    path('', views.index),
    path('index/', views.index),
]

user/urls.py
from django.urls import path, re_path
from .views import *

urlpatterns = [
    path('', user),
    path('ajax_get_user', ajax_get_user),
    path('ajax_save', ajax_save),
    path('select', select),
    path('select_word/', select_word),
    re_path(r'(?P<username>[0-9a-zA-Z_-]+?)/edit/$', edit_user_info),
    re_path(r'(?P<username>[0-9a-zA-Z_-]+?)/$', user_info),
    re_path(r'(?P<username>[0-9a-zA-Z_-]+?)/edit/$', edit_user_info)
]

word/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls import include
from word.settings import MEDIA_ROOT
from django.views.static import serve
import login.views
import captcha.views
import user.urls
import home.urls
import check.urls
import user.views
import note.urls

urlpatterns = [

    re_path(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),

    path('admin/', admin.site.urls),
    # login 模块
    path('login/', login.views.login),
    path('logout/', login.views.logout),
    path('register/', login.views.register),
    path('confirm/', login.views.user_confirm),
    path('forget/', login.views.forget),
    path('reset/', login.views.reset),
    path('ajax_reset', login.views.ajax_reset),

    # 验证码
    path('captcha/', include('captcha.urls')),
    path('ajax_val', login.views.ajax_val, name='ajax_val'),
    path('refresh', captcha.views.captcha_refresh, name='captcha-refresh'),

    # 用户
    re_path(r'user/', include(user.urls)),
    # re_path(r'user/([\w]+)/', user.views.user_info),

    # 首页
    path('', include(home.urls)),

    # 单词检测
    path('check/', include(check.urls)),

    # 笔记
    path('note/', include(note.urls))

]

login/models.py
from re import T
from django.db import models
from django.db.models.deletion import CASCADE
from enum import Enum

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=32,unique=True, null=False, verbose_name='用户名', db_index=True)
    password = models.CharField(max_length=256, null=False, verbose_name='密码')
    email = models.EmailField(verbose_name='邮箱')
    c_time = models.DateTimeField(auto_now_add=True, verbose_name='注册时间')
    has_confirmed = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.username
    
    class Meta:
        ordering = ['-c_time']
        verbose_name = '用户'
        verbose_name_plural = "用户"

# 枚举类
# class SEX(Enum):
#     F = '女'
#     M = '男'
#     S = '保密'

class UserDetail(models.Model):
    user = models.OneToOneField('User', on_delete=CASCADE)
    nickname = models.CharField(max_length=128, default='喵帕斯', verbose_name='昵称')
    gender = (
        ('male', "男"),
        ('female', "女"),
        ('other', '其它')
    )
    sex = models.CharField(max_length=32, choices=gender, default='男')
    sign = models.CharField(
        max_length=256, verbose_name='签名', default='这个人很懒，什么也没有留下！')
    avatar = models.ImageField(upload_to='img', verbose_name='头像')
    birthday = models.DateField(auto_now_add=True)
    last_edit = models.DateTimeField(auto_now=True)
    def __str__(self) -> str:
        return self.user.username + self.nickname

    class Meta:
        ordering = ['-last_edit']
        verbose_name = '用户信息'
        verbose_name_plural = "用户信息"


class ConfirmString(models.Model):
    code = models.CharField(max_length=256)
    user = models.OneToOneField('User', on_delete=CASCADE)
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.user.username + ": " + self.code

    class Meta:
        ordering = ['-c_time']
        verbose_name = '确认码'
        verbose_name_plural = "确认码"


class LoginRecord(models.Model):
    login_user = models.CharField(max_length=128, verbose_name='用户')
    login_time = models.DateTimeField(auto_now_add=True, verbose_name='登录时间')
    login_ip = models.CharField(max_length=31, verbose_name="IP")

    def __str__(self) -> str:
        return self.login_user

    class Meta:
        ordering = ['-login_time']
        verbose_name = '登录纪录'
        verbose_name_plural = "登录纪录"

class ForgetString(models.Model):
    code = models.CharField(max_length=256)
    username = models.CharField(max_length=128)
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.username + ": " + self.code

    class Meta:
        ordering = ['-c_time']
        verbose_name = '重置码'
        verbose_name_plural = "重置码"

user/models.py
from hashlib import new
from django.db import models
from django.db.models.deletion import CASCADE
import login.models


# Create your models here.
class UserChange(models.Model):
    change_user = models.CharField(max_length=128, verbose_name='修改用户')
    change_type = models.CharField(max_length=64, verbose_name='修改类型')
    change_time = models.DateTimeField(auto_now_add=True, verbose_name='修改时间')

    def __str__(self) -> str:
        return self.change_user + ": " + str(self.change_time)

    class Meta:
        ordering = ['-change_time']
        verbose_name = '修改纪录'
        verbose_name_plural = "修改纪录"


class ChangeDetail(models.Model):
    change = models.OneToOneField(UserChange, on_delete=CASCADE)
    old_nickname = models.CharField(max_length=128, verbose_name='昵称')
    gender = (
        ('male', "男"),
        ('female', "女"),
        ('other', '其它')
    )
    old_sex = models.CharField(max_length=32, choices=gender)
    old_sign = models.CharField(
        max_length=256, verbose_name='签名')
    old_avatar = models.ImageField(upload_to='img', verbose_name='头像')

    def __str__(self) -> str:
        return self.change.change_user + ' ' + self.old_nickname


class PasswordChange(models.Model):
    change_user = models.CharField(max_length=128, verbose_name='修改用户')
    old_password = models.CharField(max_length=256, verbose_name='旧密码')
    new_password = models.CharField(max_length=256, verbose_name='新密码')
    change_time = models.TimeField(auto_now_add=True, verbose_name='修改时间')

    def __str__(self) -> str:
        return self.change_user

    class Meta:
        ordering = ['-change_time']
        verbose_name = '密码纪录'
        verbose_name_plural = "密码纪录"


class UserWord(models.Model):
    username = models.CharField(max_length=128, verbose_name='username')
    word_type = models.CharField(max_length=16, verbose_name='word_type')

    def __str__(self) -> str:
        return self.username + ': ' + self.word_type



class Dynamics(models.Model):
    username = models.CharField(max_length=128, verbose_name='username')
    doing = models.CharField(max_length=512, verbose_name='doing')
    target_id = models.IntegerField(verbose_name='target_id')
    type = models.CharField(max_length=2, verbose_name='type')
    c_time = models.DateTimeField(auto_now_add=True, verbose_name='time')
    def __str__(self) -> str:
        return self.username + ": " + self.doing[:20]

   
    def add_dynamics(self, username, type="O", target_id=1000,  doing="default"):
        # type R(random) 表示随机选择，L(letter) 表示首字母， N(Note) 表示Note，S(Star) 表示收藏， C(change) 表示修改,  F(finish)表示其它 O(other) 表示其它
        type = type.upper()
        user_0 = login.models.User.objects.filter(username=username)
        if not user_0:
            return False

        dynamics = Dynamics()
        self.username = username
        self.type = type
        self.target_id = target_id
        if doing == 'default':
            if type == 'R':
                doing = 'create a new random check.'
            elif type == 'L':
                doing = 'create a new first letter check.'
            elif type == 'N':
                doing = 'create a new note.'
            elif type == 'S':
                doing = 'create a new Setence train.'
            elif type == 'C':
                doing = 'change user info.'
            elif type == 'F':
                doing = 'finish the check.'
            elif type == 'O':
                doing = 'maybe doing something.'

        self.doing = doing
        self.save()
        return True

user/views.py
import django
import login.models
from check.models import Check
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.core.paginator import InvalidPage, PageNotAnInteger, Paginator

from user.models import ChangeDetail, Dynamics, UserChange, UserWord

from .form import *


# Create your views here.
def user(request):
    if not request.session.get('is_login', None):
        Login = False
        message = '还未登录，请前往登录！'
        return render(request, 'buff.html', locals())
    username = request.session.get('user_name')
    return redirect('/user/{}/'.format(username))


def user_info(request, username):
    try:
        user = login.models.User.objects.get(username=username)
    except:
        return render(request, 'error.html', locals())

    try:
        user_detail = login.models.UserDetail.objects.get(user=user)
    except:
        user_detail = login.models.UserDetail(user=user, nickname=username, sex='其它', sign='这个人很懒，什么也没有留下')
        user_detail.save()
    try:
        user_word = UserWord.objects.get(username=username)
    except:
        user_word = UserWord()
        user_word.username = username
        user_word.word_type = 'cet-4'
        user_word.save()

    word_type = user_word.word_type
    avatar = user_detail.avatar

    dynamicses = Dynamics.objects.filter(username=username)
    checks = Check.objects.filter(username=username)
    word_num = 0
    for c in checks:
        word_num += c.check_num
    note_num = 1
    check_num = len(checks)
    return render(request, 'user/user.html', locals())
    # dynamics_pages = Paginator(dynamicses, 10)
    # check_pages = Paginator(checks, 10)
    # if request.method == 'GET':
    #     dynamicses = dynamics_pages.page(1)
    #     checks = check_pages.page(1)
    #     return render(request, 'user/user.html', locals())
    # if request.is_ajax():
    #     page = request.GET.get('page')
    #     try:
    #         dynamicses = dynamics_pages.page(page)
    #     # 如果页数不是整数，返回第一页
    #     except PageNotAnInteger:
    #         dynamicses = dynamics_pages.page(1)
    #     # 如果页数不存在/不合法，返回最后一页
    #     except InvalidPage:
    #         dynamicses = dynamics_pages.page(1)
    #     dynamicses_li = list(dynamicses.object_list.values())
    #     # 分别为是否有上一页false/true，是否有下一页false/true，总共多少页，当前页面的数据
    #     result = {'has_previous': dynamicses.has_previous(),
    #               'has_next': dynamicses.has_next(),
    #               'num_pages': dynamicses.paginator.num_pages,
    #               'dynamicses_li': dynamicses_li}
    #     return JsonResponse(result)


def edit_user_info(request, username):
    if not request.session.get('is_login', None):
        message = '还未登录，请登录后再访问！'
        url = '/login/'
        return render(request, 'buff.html', locals())
    username_1 = request.session.get('user_name')
    if username != username_1:
        message = '无效的页面，将返回首页！'
        url = '/index/'
        return render(request, 'buff.html', locals())
    # print(username, username_1)
    user = login.models.User.objects.get(username=username)
    # user_detail = login.models.UserDetail.objects.get(user=user)
    # user_detail_form = UserDetailForm()
    # user_detail_form.avatar = user_detail.avatar
    # user_detail_form.birthday = user_detail.birthday
    # user_detail_form.nickname = user_detail.nickname
    # user_detail_form.sex = user_detail.sex
    # user_detail_form.sign = user_detail.sign

    return render(request, 'user/edit_profile.html', locals())


def select_word(request):
    if not request.session.get('is_login', None):
        Login = False
        message = '还未登录，请登录后再访问！'
        url = '/login/'
        return render(request, 'buff.html', locals())
    username = request.session.get('user_name')
    try:
        user_word = UserWord.objects.get(username=username)
    except:
        user_word = UserWord()
        user_word.username = username
        user_word.word_type = 'cet-4'
        user_word.save()
    word_type = user_word.word_type
    return render(request, 'user/select_word.html', locals())


def select(request):
    if not request.session.get('is_login', None):
        data = {
            'status': 0, 'message': 'Please <a href="/login">Login</a> !', }
        return JsonResponse(data)

    if not request.is_ajax():
        data = {'status': 0, 'message': 'Maybe submit again?', }
        return JsonResponse(data)

    username = request.session.get('user_name')
    try:
        user_word = UserWord.objects.get(username=username)
    except:
        user_word = UserWord()
        user_word.username = username
    word_type = request.POST.get('type')
    user_word.word_type = word_type
    user_word.save()
    data = {'status': 1,
            'message': 'Change Success! Go to <a href="/check">learn</a> !'}
    dy = Dynamics()
    dy.add_dynamics(username, type="C", doing="change the word type for {}".format(word_type))
    return JsonResponse(data)


def ajax_get_user(request):
    if not request.is_ajax():
        return JsonResponse({'status': 0, 'message': 'Maybe have some error!'})
    if not request.session.get('is_login', None):
        return JsonResponse({'status': -1, 'message': 'Please login!'})
    username = request.session.get('user_name')
    user = login.models.User.objects.get(username=username)
    user_detail = login.models.UserDetail.objects.filter(user=user)
    if not user_detail:
        ud = login.models.UserDetail()
        ud.user = user
        ud.nickname = username + user.id
        ud.sex = 'other'
        ud.avatar = 'img/avatar.jpg'
        ud.save()
    else:
        ud = user_detail[0]

    return JsonResponse({'status': 1, 'avatar': str(ud.avatar), 'username': username,'nickname':ud.nickname, 'sign':ud.sign, 'birthday': str(ud.birthday), 'sex': str(ud.sex)})


def ajax_save(request):
    if not request.is_ajax():
        return JsonResponse({'status': 0, 'message': 'Maybe Request again?'})
    if not request.session.get('is_login', None):
        return JsonResponse({'status': 0, 'message': 'Please Login!'})

    # print(request.POST)
    username = request.session.get('user_name')
    user_0 = login.models.User.objects.get(username=username)
    user_detail = login.models.UserDetail.objects.get(user=user_0)

    uc = UserChange()
    uc.change_user = username
    uc.change_type = 'C'
    uc.save()
    cd = ChangeDetail()
    cd.change = uc
    cd.old_avatar = user_detail.avatar
    cd.old_nickname = user_detail.nickname
    cd.old_sign = user_detail.sign
    cd.old_sex = user_detail.sex
    cd.save()
    user_detail.nickname = request.POST.get('nickname')
    user_detail.sign = request.POST.get('sign')
    user_detail.sex = request.POST.get('radio_sex')
    user_detail.birthday = request.POST.get('birthday')
    try:
        img = request.FILES['img_file']
        user_detail.avatar = img
    except ( django.utils.datastructures.MultiValueDictKeyError) as e:
        print(e)
    user_detail.save()
    dynamics = Dynamics()
    dynamics.add_dynamics(username, type="C", doing="edit the profile")
    return JsonResponse({'status': 1, 'message': 'Change Success!', 'username': username})


def add_dynamics(username, type="O", target_id=1000,  doing="default"):
    # type R(random) 表示随机选择，L(letter) 表示首字母， N(Note) 表示Note，S(setence) 表示句子， C(change) 表示修改, M(mark) 表示收藏, F(finish)表示其它 O(other) 表示其它
    type = type.upper()
    user_0 = login.models.User.objects.filter(username=username)
    if not user_0:
        return False
    
    dynamics = Dynamics()
    dynamics.username = username
    dynamics.type = type
    dynamics.target_id = target_id
    if doing == 'default':
        if type == 'R':
            doing = 'create a new random check.'
        elif type == 'L':
            doing = 'create a new first letter check.'
        elif type == 'N':
            doing = 'create a new note.'
        elif type == 'S':
            doing = 'create a new Setence train.'
        elif type == 'C':
            doing = 'change user info.'
        elif type == 'F':
            doing = 'finish the check.'
        elif type == 'O':
            doing = 'maybe doing something.'

    dynamics.doing = doing
    dynamics.save()
    return True


        

    

templates/user/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ username }} - 编辑资料
{% endblock title %}


<!-- {% block login %}

{% endblock login %} -->
{% block style %}
<!-- <link href="https://cdn.bootcdn.net/ajax/libs/bootstrap-fileinput/5.1.5/css/fileinput-rtl.min.css" rel="stylesheet"> -->
{% endblock style %}

{% block body %}
<div class="container">
    <form action="" id="edit_form" class="form-horizontal">
        {% csrf_token %}
        <div class="form-group">
            <div id="previewDiv" class=" col-sm-2">
                <img src="" alt="预览" id="previewImg" class="img-thumbnail img-responsive ">
                <!--进度条-->
                <div id="progress" style="color: black"></div>

            </div>
            <div class="col-md-10 col-md-3">
                <!-- <input type="file" name="avatar_img" id="upload_img" accept="image/png, image/jpeg" class="" value=""> -->
                <input type="button" id="chooseImg" value="choose" class="btn btn-info btn-sm">
            </div>
        </div>
        <div class="form-group">
            <label for="id_nickname" class="col-sm-2  control-label">Nickname</label>
            <div class="col-sm-10 col-md-3">
                <input type="text" class="form-control" name="nickname" class="form-control" placeholder="Nickname"
                    maxlength="128" required id="id_nickname">
            </div>
        </div>
        <div class="form-group">
            <label for="id_sign" class="col-sm-2 control-label">Sign</label>
            <div class="col-sm-10 col-md-3">
                <textarea class="form-control" required id="id_sign" name="sign" placeholder="Sign" rows="3"></textarea>
                <!-- <input type="text" class="form-control" name="sign" class="form-control" placeholder="Sign" -->
                    <!-- maxlength="128" required id="id_sign"> -->
                <!-- <textarea name="sign" id="id_sign_area" cols="40" class="textarea" rows="2"></textarea> -->
            </div>
        </div>

        <div class="form-group">
            <label for="id_sex_0" class="col-sm-2 control-label">Gender:</label>
            <div class="col-sm-10 col-md-3">
                <div class="radio">
                    <label>
                        <input type="radio" name="radio_sex" id="id_male" value="male">
                        male
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="radio_sex" id="id_female" value="female">
                        female
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="radio_sex" id="id_other" value="other">
                        other
                    </label>
                </div>
            </div>
        </div>


        <div class="form-group">
            <label for="id_birthday" class="col-sm-2 control-label">birthday: </label>
            <div class="col-sm-10 col-md-3">
                <input type="date" name="birthday" class="form-control" required id="id_birthday">
            </div>
        </div>


        <div class="form-group">
            <div class="col-sm-offset-2 col-md-offset-2 col-sm-10">
                <button type="button" class="btn btn-primary" data-toggle="modal"
                    data-target="#ConfirmModal">Save</button>
            </div>
        </div>

        <div class="form-group hidden">
            <!-- <input type="file" name="test" id=""> -->
            <input type="file" id="selectImg" name="img_file">
            <input type="hidden" name="imgId">
        </div>
        <div class="modal fade" id="ConfirmModal" tabindex="-1" role="dialog" aria-labelledby="ConfirmModalLabel"
            aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="resetModalLabel">confirm</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            &times;
                        </button>
                    </div>
                    <div class="modal-body">Confirm the change? </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal" id="change_cancel">
                            No
                        </button>
                        <button type="button" class="btn btn-primary" id="change_submit">Yes</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

</div>

{% endblock body %}

{% block script %}
<!-- <scriptsrc="https://cdn.bootcdn.net/ajax/libs/bootstrap-fileinput/5.1.5/js/fileinput.js"></script> -->
<script>
    function set_info() {
        $.ajax({
            url: "/user/ajax_get_user",
            data: {},
            type: "get",
            datatype: 'json',
            success: function (result) {
                if (result['status'] === 0) {
                    alert(result['message']);
                }
                else if (result['status'] === -1) {
                    // $("#unlogin_li").removeClass('hidden');
                    // $("#login_li").addClass('hidden');
                    // $("#avatar_img").attr('src', '/media/img/default.jpg');
                }
                else {
                    $("#id_nickname").attr("value", result["nickname"]);
                    $("#id_sign").text(result["sign"]);
                    $("#id_birthday").attr("value", result["birthday"]);
                    $("#previewImg").attr('src', '/media/' + result['avatar']);
                    sex = result['sex']
                    if (sex === 'male') {
                        $('#id_male').prop('checked', 'checked')
                    }
                    else if (sex === 'female') {
                        $('#id_female').prop('checked', 'checked')
                    }
                    else {
                        $('#id_other').attr('checked', true)
                    }
                }
            },
            error: function (result) {
            }
        })
    }

    set_info();
    function preview(imgobj, previewImgId, previewDivId) {
        var accept = /^(.+)\.(jpg||jpeg||png||gif)$/g;
        var browserVersion = window.navigator.userAgent.toLowerCase();
        if (accept.test(imgobj.value)) {
            //上传为可接受图片格式
            if (imgobj.files) {
                //上传了图片文件
                if (window.FileReader) {//html5实现文件上传,兼容ie10及以上 chrome，ff7+
                    var reader = new FileReader();
                    reader.onload = function () {
                        $("#previewImg").attr("src", this.result);
                    }
                    reader.readAsDataURL(imgobj.files[0]);
                    //将文件以data：url形式读取，写入到result属性中，没有返回值
                    // reader.onprogress = function(e) { 
                    //  document.getElementById("progress").textContent = (e.loaded/imgobj.files[0].size).toFixed(2)*100+"%"; 
                    //  }
                }
            }
            else if (browserVersion.indexOf("firefox") > -1) {
                //不支持html5；兼容低版本火狐浏览器
                $("#previewImg").attr("src", imgobj.files[0].getAsDataURL());

            }
            else if (browserVersion.indexOf("msie") > -1) {
                //ie浏览器
                if (browserVersion.indexOf("msie 6") > -1) {
                    //兼容ie6
                    $("#previewImg").attr("src", imgobj.value);
                }
                else {
                    //ie[7-9]因为该版本浏览器处于安全性考虑，屏蔽了上传文件的真是本地地址，使用以下获取真实地址
                    //在ie中使用滤镜进行预览图片，
                    imgobj.select();
                    if (browserVersion.indexOf("msie 9") > -1) {
                        //ie9中必须将焦点从文本域移开，否则拒绝document.selection.createRange().text
                        $("#previewImg").focus();
                        //如果上传控件在框架中，imgobj.blur并不能达到目的，所以可以将任意元素聚焦来达到目的。
                    }
                }
            }
            else {
                document.getElementById(previewImgId).setAttribute("src", imgobj.value);
            }
        }
        else {
            alert("图片格式不符合，请选择jpg/png/gif/jpeg格式的图片");
            imgobj.value = ""; //清空选中文件
            if (browserVersion.indexOf("msie") > -1) {//兼容ie9及以下浏览器
                imgobj.select();
                document.selection.clear();
            }
        }
    }

    $(document).ready(
        $(function () {
            $("#chooseImg").click(function () {
                $("#selectImg").click().select();
            })
            $("#selectImg").change(function () {
                preview(this, $("#previewImg"), "previewDiv");
            })

            $("#upload_img").change(function () {
                preview(this, $("#edit_avatar"), "previewDiv");
            })
            $("#change_submit").click(function () {
                $('#change_cancel').click();
                $('#change_cancel').click();
                // console.log("LKJSLKDJL")
                // console.log(typeof ($("#edit_form").serialize()))
                var form_data = new FormData($("#edit_form")[0])
                $.ajax({
                    url: "/user/ajax_save",
                    // data: $("#edit_form").serialize(),
                    data: form_data,
                    type: "post",
                    datatype: 'json',
                    contentType: false, //表示不处理数据
                    processData: false,
                    success: function (result) {
                        console.log(result['status'])
                        if (result['status'] === 0) {
                        }
                        else {
                            setTimeout(function(){
                            alert(result['message']);
                            location.href = '/user/' + result['username']
                            }, 1000)
                        }
                    },
                    error: function (result) {
                    }
                })

            })
        })
    )
</script>

{% endblock script %}